version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
    networks:
      - backend

  graphql-server:
    build: ./graphql-server
    ports:
      - "4000:4000"
    volumes:
      - ./graphql-server:/app
    networks:
      - backend

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - backend

networks:
  backend:
    driver: bridge
